# Generated by Django 6.0.5 on 2026-05-13 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocations', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='subjects.courseoutcome')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
                ('subject_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='allocations.subjectallocation')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.surveytemplate')),
            ],
            options={
                'unique_together': {('student', 'subject_allocation', 'co')},
            },
        ),
    ]
