# Generated by Django 6.0.5 on 2026-05-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocations', '0001_initial'),
        ('departments', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttainmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_marks_pct', models.DecimalField(decimal_places=2, default=60.0, help_text='% of max marks a student must score to attain a CO', max_digits=5)),
                ('level3_student_pct', models.DecimalField(decimal_places=2, default=70.0, help_text='% of students that must attain for Level 3', max_digits=5)),
                ('level2_student_pct', models.DecimalField(decimal_places=2, default=60.0, help_text='% of students that must attain for Level 2', max_digits=5)),
                ('level1_student_pct', models.DecimalField(decimal_places=2, default=50.0, help_text='% of students that must attain for Level 1', max_digits=5)),
                ('direct_weightage', models.DecimalField(decimal_places=2, default=80.0, help_text='Weight of direct attainment in final CO attainment', max_digits=5)),
                ('indirect_weightage', models.DecimalField(decimal_places=2, default=20.0, help_text='Weight of indirect (survey) attainment in final CO attainment', max_digits=5)),
                ('target_co_level', models.IntegerField(default=2)),
                ('target_po_attainment', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('cia_best_of', models.IntegerField(default=2, help_text='Take best N out of 3 CIAs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attainment_config', to='departments.department')),
            ],
            options={
                'verbose_name': 'Attainment Configuration',
                'db_table': 'attainment_config',
            },
        ),
        migrations.CreateModel(
            name='PSOAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attainment_value', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('attainment_level', models.IntegerField(null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pso_attainments', to='subjects.academicyear')),
                ('pso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainments', to='departments.programspecificoutcome')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pso_attainments', to='departments.section')),
            ],
            options={
                'verbose_name': 'PSO Attainment',
                'db_table': 'pso_attainment',
            },
        ),
        migrations.CreateModel(
            name='COAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_attained', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('attainment_percentage', models.DecimalField(decimal_places=2, help_text='% of students who attained the CO', max_digits=5, null=True)),
                ('direct_attainment', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('indirect_attainment', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('final_attainment', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('attainment_level', models.IntegerField(null=True)),
                ('target_attainment', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('target_achieved', models.BooleanField(null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainments', to='subjects.courseoutcome')),
                ('subject_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_attainments', to='allocations.subjectallocation')),
            ],
            options={
                'verbose_name': 'CO Attainment',
                'db_table': 'co_attainment',
                'indexes': [models.Index(fields=['co'], name='co_attainme_co_id_0a4aad_idx'), models.Index(fields=['subject_allocation'], name='co_attainme_subject_09fa30_idx')],
                'unique_together': {('co', 'subject_allocation')},
            },
        ),
        migrations.CreateModel(
            name='POAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(null=True)),
                ('attainment_value', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('attainment_level', models.IntegerField(null=True)),
                ('target_attainment', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('target_achieved', models.BooleanField(null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_attainments', to='subjects.academicyear')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainments', to='departments.programoutcome')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_attainments', to='departments.section')),
            ],
            options={
                'verbose_name': 'PO Attainment',
                'db_table': 'po_attainment',
                'indexes': [models.Index(fields=['po'], name='po_attainme_po_id_55cb0c_idx'), models.Index(fields=['section', 'academic_year'], name='po_attainme_section_dc7787_idx')],
            },
        ),
    ]
