# Generated by Django 6.0.5 on 2026-05-14 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0002_initial'),
        ('attainment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTakenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_performing_cos', models.JSONField(default=list, help_text='List of CO numbers that were below target')),
                ('root_cause', models.TextField(help_text='Reason for low attainment')),
                ('proposed_actions', models.TextField(help_text='Corrective measures to be taken')),
                ('action_type', models.CharField(blank=True, help_text='Remedial, Content Beyond Syllabus, etc.', max_length=100)),
                ('implementation_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('REVIEWED', 'Reviewed'), ('IMPLEMENTED', 'Implemented'), ('EFFECTIVE', 'Proved Effective')], default='DRAFT', max_length=20)),
                ('hod_remarks', models.TextField(blank=True)),
                ('effectiveness_score', models.IntegerField(blank=True, help_text='Score 1-5 on how effective the actions were in next cycle', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atr', to='allocations.subjectallocation')),
            ],
            options={
                'verbose_name': 'Action Taken Report',
                'db_table': 'action_taken_report',
            },
        ),
    ]
