# Generated by Django 6.0.5 on 2026-05-14 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocations", "0003_subjectallocation_approval_status_and_more"),
        ("attainment", "0002_actiontakenreport"),
        ("students", "0001_initial"),
        ("subjects", "0002_subject_regulation_alter_subject_subject_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseExitSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "target_percentage",
                    models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject_allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_survey",
                        to="allocations.subjectallocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Exit Survey",
                "db_table": "course_exit_survey",
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1 — Low"), (2, "2 — Medium"), (3, "3 — High")]
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "co",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.courseoutcome",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="attainment.courseexitsurvey",
                    ),
                ),
            ],
            options={
                "db_table": "survey_response",
                "unique_together": {("survey", "student", "co")},
            },
        ),
    ]
