# Generated by Django 5.2.14 on 2026-05-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attainment', '0003_courseexitsurvey_surveyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attainmentconfig',
            name='cia_best_of',
        ),
    ]
