# Generated by Django 5.2.14 on 2026-05-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_department_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this HR staff member can upload marks for.', related_name='hr_staff_members', to='departments.department'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='is_hr_staff',
            field=models.BooleanField(default=False, help_text='When True, this faculty member acts as an HR mark-entry operator.'),
        ),
    ]
