# Generated by Django 5.2.14 on 2026-06-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_facultyprofile_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='is_hr_staff',
        ),
    ]
