# Generated by Django 6.0.5 on 2026-05-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('INTERNAL', 'Internal Assessment'), ('EXTERNAL', 'External Assessment'), ('CONTINUOUS', 'Continuous Assessment'), ('PROJECT', 'Project Assessment')], max_length=20)),
                ('default_max_marks', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('weightage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_system', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Assessment Type',
                'db_table': 'assessment_type',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SubjectAssessmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('passing_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assessment Configuration',
                'db_table': 'subject_assessment_config',
            },
        ),
        migrations.CreateModel(
            name='COAssessmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of this assessment covering this CO', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_mappings', to='allocations.assessmenttype')),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_mappings', to='subjects.courseoutcome')),
            ],
            options={
                'verbose_name': 'CO-Assessment Mapping',
                'db_table': 'co_assessment_mapping',
            },
        ),
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='subjects.academicyear')),
            ],
            options={
                'verbose_name': 'Subject Allocation',
                'db_table': 'subject_allocation',
            },
        ),
    ]
