# Generated by Django 6.0.5 on 2026-05-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocations', '0001_initial'),
        ('departments', '0001_initial'),
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectallocation',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='users.facultyprofile'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='departments.section'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='coassessmentmapping',
            name='subject_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_assessment_mappings', to='allocations.subjectallocation'),
        ),
        migrations.AddField(
            model_name='subjectassessmentconfig',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_configs', to='allocations.assessmenttype'),
        ),
        migrations.AddField(
            model_name='subjectassessmentconfig',
            name='subject_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_configs', to='allocations.subjectallocation'),
        ),
        migrations.AddIndex(
            model_name='subjectallocation',
            index=models.Index(fields=['faculty'], name='subject_all_faculty_385e46_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectallocation',
            index=models.Index(fields=['section', 'academic_year'], name='subject_all_section_47b3d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectallocation',
            unique_together={('subject', 'section', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectassessmentconfig',
            unique_together={('subject_allocation', 'assessment_type')},
        ),
    ]
