# Generated by Django 6.0.5 on 2026-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectallocation",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subjectallocation",
            name="hod_remarks",
            field=models.TextField(blank=True),
        ),
    ]
