# Generated by Django 6.0.5 on 2026-05-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0003_subjectallocation_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectassessmentconfig',
            name='weightage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
