# Generated by Django 5.2.14 on 2026-05-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0004_add_weightage_to_assessment_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectallocation',
            name='staff_mark_entry_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, HR staff assigned to this department can upload marks for this subject.'),
        ),
    ]
