# Generated by Django 5.2.14 on 2026-06-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0005_add_staff_mark_entry_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectallocation',
            name='staff_mark_entry_enabled',
        ),
    ]
