# Generated by Django 6.0.5 on 2026-05-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CHANGE_PASSWORD', 'Change Password'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('MARKS_ENTRY', 'Marks Entry'), ('MARKS_UPDATE', 'Marks Update'), ('EXCEL_UPLOAD', 'Excel Upload'), ('CALCULATE_ATTAINMENT', 'Calculate Attainment'), ('EXPORT_REPORT', 'Export Report'), ('CONFIG_CHANGE', 'Configuration Change')], db_index=True, max_length=50)),
                ('table_name', models.CharField(blank=True, max_length=100)),
                ('record_id', models.BigIntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
