# Generated by Django 5.2.14 on 2026-05-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_staff_role_and_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('hod', 'HOD / Department Admin'), ('faculty', 'Faculty'), ('iqac', 'IQAC')], default='faculty', max_length=20),
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
