# Generated by Django 6.0.5 on 2026-05-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'db_table': 'academic_year',
                'ordering': ['-label'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=30, unique=True)),
                ('subject_name', models.CharField(max_length=300)),
                ('semester', models.IntegerField()),
                ('credits', models.IntegerField(default=3)),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Laboratory'), ('PROJECT', 'Project'), ('ELECTIVE', 'Elective'), ('AUDIT', 'Audit Course')], default='THEORY', max_length=30)),
                ('lecture_hours', models.IntegerField(default=3)),
                ('tutorial_hours', models.IntegerField(default=0)),
                ('practical_hours', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='departments.department')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subject',
                'ordering': ['semester', 'subject_code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_number', models.IntegerField()),
                ('co_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('bloom_level', models.CharField(choices=[('Remember', 'Remember (L1)'), ('Understand', 'Understand (L2)'), ('Apply', 'Apply (L3)'), ('Analyze', 'Analyze (L4)'), ('Evaluate', 'Evaluate (L5)'), ('Create', 'Create (L6)')], default='Apply', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_outcomes', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Course Outcome',
                'db_table': 'course_outcome',
                'ordering': ['co_number'],
            },
        ),
        migrations.CreateModel(
            name='COPSOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_level', models.IntegerField(choices=[(1, '1 — Low'), (2, '2 — Medium'), (3, '3 — High')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_mappings', to='departments.programspecificoutcome')),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pso_mappings', to='subjects.courseoutcome')),
            ],
            options={
                'verbose_name': 'CO-PSO Mapping',
                'db_table': 'co_pso_mapping',
                'unique_together': {('co', 'pso')},
            },
        ),
        migrations.CreateModel(
            name='COPOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_level', models.IntegerField(choices=[(1, '1 — Low'), (2, '2 — Medium'), (3, '3 — High')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_mappings', to='departments.programoutcome')),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_mappings', to='subjects.courseoutcome')),
            ],
            options={
                'verbose_name': 'CO-PO Mapping',
                'db_table': 'co_po_mapping',
                'indexes': [models.Index(fields=['co'], name='co_po_mappi_co_id_29a2f3_idx'), models.Index(fields=['po'], name='co_po_mappi_po_id_c830c2_idx')],
                'unique_together': {('co', 'po')},
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_code'], name='subject_subject_71a7de_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['department', 'semester'], name='subject_departm_ce3dcd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseoutcome',
            unique_together={('subject', 'co_number')},
        ),
    ]
