# Generated by Django 6.0.5 on 2026-05-14 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_regulation_batch_regulation_programme_regulation_and_more'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='regulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='departments.regulation'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Laboratory'), ('INTEGRATED', 'Theory + Lab'), ('PROJECT', 'Project'), ('ELECTIVE', 'Elective'), ('AUDIT', 'Audit Course')], default='THEORY', max_length=30),
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapped_cos', models.ManyToManyField(blank=True, related_name='experiments', to='subjects.courseoutcome')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='subjects.subject')),
            ],
            options={
                'db_table': 'experiment',
                'ordering': ['exp_number'],
                'unique_together': {('subject', 'exp_number')},
            },
        ),
        migrations.CreateModel(
            name='LabComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_marks', models.IntegerField(default=10)),
                ('weightage', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_components', to='subjects.subject')),
            ],
            options={
                'db_table': 'lab_component',
                'unique_together': {('subject', 'name')},
            },
        ),
    ]
