# Generated by Django 6.0.5 on 2026-05-13 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocations', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='excel_uploads/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_total', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_uploads', to='allocations.assessmenttype')),
                ('subject_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_uploads', to='allocations.subjectallocation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excel Upload Log',
                'db_table': 'excel_upload_log',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=10)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mappings', to='allocations.assessmenttype')),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mappings', to='subjects.courseoutcome')),
                ('subject_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_co_mappings', to='allocations.subjectallocation')),
            ],
            options={
                'verbose_name': 'Question-CO Mapping',
                'db_table': 'question_co_mapping',
                'unique_together': {('subject_allocation', 'assessment_type', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_absent', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='allocations.assessmenttype')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
                ('subject_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='allocations.subjectallocation')),
            ],
            options={
                'verbose_name': 'Student Mark',
                'db_table': 'student_mark',
                'indexes': [models.Index(fields=['student'], name='student_mar_student_b49ff5_idx'), models.Index(fields=['subject_allocation'], name='student_mar_subject_315387_idx'), models.Index(fields=['assessment_type'], name='student_mar_assessm_d67f72_idx'), models.Index(fields=['subject_allocation', 'assessment_type'], name='student_mar_subject_aa34be_idx')],
                'unique_together': {('student', 'subject_allocation', 'assessment_type')},
            },
        ),
        migrations.CreateModel(
            name='StudentQuestionMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('question_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='marks.questioncomapping')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_marks', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Question Mark',
                'db_table': 'student_question_mark',
                'unique_together': {('student', 'question_mapping')},
            },
        ),
    ]
