# Generated by Django 5.2.14 on 2026-06-01 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_add_is_first_year_to_department'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='target_department',
            field=models.ForeignKey(blank=True, help_text='For S&H students: the engineering department they will be transferred to at the start of their second year.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_students', to='departments.department'),
        ),
    ]
