import ExcelJS from 'exceljs'

// ─── Brand palette ────────────────────────────────────────────────────────────
export const COLORS = {
  primary:   '1A1F4E',
  secondary: '4A52A3',
  teal:      '0D6E5A',
  amber:     'B7760A',
  red:       'E24B4A',
  lightGray: 'F4F5F8',
  white:     'FFFFFF',
  border:    'E8EAF2',
  // Soft tints for attainment cells
  tealLight:  'E0F7F2',
  amberLight: 'FEF4E4',
  redLight:   'FCEBEB',
}

// ─── Cell style helpers ───────────────────────────────────────────────────────

export function applyHeaderStyle(
  cell: ExcelJS.Cell,
  opts?: { fontSize?: number }
): void {
  cell.fill   = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${COLORS.primary}` } }
  cell.font   = { color: { argb: `FF${COLORS.white}` }, bold: true, size: opts?.fontSize ?? 11 }
  cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: false }
  cell.border = {
    top:    { style: 'thin', color: { argb: `FF${COLORS.border}` } },
    left:   { style: 'thin', color: { argb: `FF${COLORS.border}` } },
    bottom: { style: 'thin', color: { argb: `FF${COLORS.border}` } },
    right:  { style: 'thin', color: { argb: `FF${COLORS.border}` } },
  }
}

export function applySubHeaderStyle(cell: ExcelJS.Cell): void {
  cell.fill   = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${COLORS.secondary}` } }
  cell.font   = { color: { argb: `FF${COLORS.white}` }, size: 10 }
  cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true }
}

export function applyDataRowStyle(cell: ExcelJS.Cell, isAlt: boolean): void {
  cell.fill   = { type: 'pattern', pattern: 'solid',
                  fgColor: { argb: `FF${isAlt ? COLORS.lightGray : COLORS.white}` } }
  cell.font   = { color: { argb: 'FF1A1F4E' }, size: 10 }
  cell.border = {
    bottom: { style: 'thin', color: { argb: `FF${COLORS.border}` } },
  }
}

export function applyAttainmentStyle(
  cell: ExcelJS.Cell,
  level: 'met' | 'near' | 'below'
): void {
  const cfg = {
    met:   { bg: COLORS.tealLight,  fg: COLORS.teal },
    near:  { bg: COLORS.amberLight, fg: COLORS.amber },
    below: { bg: COLORS.redLight,   fg: COLORS.red },
  }[level]

  cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${cfg.bg}` } }
  cell.font = { color: { argb: `FF${cfg.fg}` }, bold: true, size: 10 }
  cell.alignment = { horizontal: 'center', vertical: 'middle' }
}

// ─── Institution header (rows 1–4) ───────────────────────────────────────────

export function addInstitutionHeader(
  sheet: ExcelJS.Worksheet,
  data: {
    institution: string
    department:  string
    title:       string
    academicYear: string
  }
): void {
  const totalCols = sheet.columnCount || 10

  const merge = (row: number, col1: number, col2: number) =>
    sheet.mergeCells(row, col1, row, col2)

  // Row 1 — Institution name
  merge(1, 1, totalCols)
  const r1 = sheet.getRow(1)
  r1.height = 24
  const c1 = sheet.getCell(1, 1)
  c1.value = data.institution
  c1.font  = { color: { argb: `FF${COLORS.primary}` }, bold: true, size: 14 }
  c1.alignment = { horizontal: 'center', vertical: 'middle' }

  // Row 2 — Department
  merge(2, 1, totalCols)
  sheet.getRow(2).height = 20
  const c2 = sheet.getCell(2, 1)
  c2.value = data.department
  c2.font  = { size: 12 }
  c2.alignment = { horizontal: 'center', vertical: 'middle' }

  // Row 3 — Report title
  merge(3, 1, totalCols)
  sheet.getRow(3).height = 20
  const c3 = sheet.getCell(3, 1)
  c3.value = data.title
  c3.font  = { color: { argb: `FF${COLORS.secondary}` }, bold: true, size: 12 }
  c3.alignment = { horizontal: 'center', vertical: 'middle' }

  // Row 4 — Generated date + academic year
  merge(4, 1, totalCols)
  sheet.getRow(4).height = 18
  const c4 = sheet.getCell(4, 1)
  c4.value = `Academic Year: ${data.academicYear}  |  Generated: ${new Date().toLocaleDateString('en-IN')}`
  c4.font  = { color: { argb: 'FF9398B0' }, size: 10 }
  c4.alignment = { horizontal: 'center', vertical: 'middle' }
  c4.border = { bottom: { style: 'thin', color: { argb: `FF${COLORS.border}` } } }
}

// ─── Column widths ────────────────────────────────────────────────────────────

export function setColumnWidths(sheet: ExcelJS.Worksheet, widths: number[]): void {
  widths.forEach((w, i) => {
    const col = sheet.getColumn(i + 1)
    col.width = w
  })
}

// ─── Page footer ─────────────────────────────────────────────────────────────

export function addPageFooter(sheet: ExcelJS.Worksheet, lastRow: number): void {
  const totalCols = sheet.columnCount || 10
  sheet.mergeCells(lastRow + 2, 1, lastRow + 2, totalCols)
  const cell = sheet.getCell(lastRow + 2, 1)
  cell.value = `Generated by OBE Attain  |  ${new Date().toLocaleString('en-IN')}`
  cell.font  = { size: 9, color: { argb: 'FF9398B0' } }
  cell.alignment = { horizontal: 'right' }
}

// ─── Freeze header rows ───────────────────────────────────────────────────────

export function freezeHeaderRows(sheet: ExcelJS.Worksheet, rows: number): void {
  sheet.views = [{ state: 'frozen', ySplit: rows, xSplit: 0 }]
}

// ─── Write buffer ─────────────────────────────────────────────────────────────

export async function writeWorkbookBuffer(wb: ExcelJS.Workbook): Promise<Buffer> {
  return Buffer.from(await wb.xlsx.writeBuffer())
}
