# Generated by Django 6.0.5 on 2026-05-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('academic_rules', models.JSONField(default=dict, help_text='JSON mapping for weightages, CIA/ESE rules, and passing criteria.')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regulation',
                'db_table': 'regulation',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='regulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='departments.regulation'),
        ),
        migrations.AddField(
            model_name='programme',
            name='regulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes', to='departments.regulation'),
        ),
        migrations.CreateModel(
            name='ProgrammeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_structure', models.JSONField(default=list)),
                ('po_customizations', models.JSONField(default=dict)),
                ('pso_customizations', models.JSONField(default=dict)),
                ('attainment_thresholds', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='departments.programme')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_templates', to='departments.regulation')),
            ],
            options={
                'verbose_name': 'Programme Template',
                'db_table': 'programme_template',
                'unique_together': {('programme', 'regulation')},
            },
        ),
    ]
