# Generated by Django 5.2.14 on 2026-06-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_first_year',
            field=models.BooleanField(default=False, help_text='Mark True for Science & Humanities (S&H) departments that teach first-year students across all engineering branches.'),
        ),
    ]
